source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "jekyll-theme-chirpy", "~> 7.0"

gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-last-modified-at"
gem "jekyll-redirect-from"
gem "jekyll-archives"
gem "jekyll-paginate"
gem "jekyll-include-cache"

gem "wdm", ">= 0.1.0"